# Configuração do typos (spell check)
[default]
extend-ignore-identifiers-re = [
    "Kayquews",
    "kayquews",
    "KayqueWs",
    "kayquexf",
    "Kayque",
    "kayque",
    "Oie",
    "melhro",
    "brach",
    "dele",
    "Pergunte-me",
    "Acredito",
    "Gosto",
    "adoro",
    "Sou",
    "Atualmente",
    "Pronome",
    "apaixonado",
    "tecnologia",
    "desenvolvedor",
    "entusiasta",
    "compartilhar",
    "conhecimento",
    "transformar",
    "mudança",
    "trabalhar",
    "equipe",
    "desafios",
    "crescer",
    "aprendendo",
    "desenvolvimento",
    "mobile",
    "JavaScript",
    "Python",
    "React",
    "memes",
    "café",
    "contribuições",
    "contato",
    "estatísticas",
    "seja",
    "bem-vindo",
    "sobre",
    "ferramentas",
    "conheço",
    "escuro",
    "brilhante",
    "cobra",
    "velocidade",
    "aumentada",
    "padrão",
    "texto",
    "aparece",
    "quando",
    "come",
    "trocar",
    "cores",
    "vermelho",
    "verde",
    "atualizar",
    "roda",
    "todo",
    "dia",
    "meia-noite",
    "linkedin",
    "instagram"
]

[files]
extend-exclude = [
    "*.svg",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "node_modules/",
    ".git/",
    "output/"
]