name: Feature Request
description: Sugira uma nova funcionalidade ou melhoria
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova feature! Por favor, preencha os campos abaixo para nos ajudar a entender sua solicitação.

  - type: textarea
    id: feature-description
    attributes:
      label: Descrição da Feature
      description: Descreva claramente a feature que você gostaria de ver implementada
      placeholder: "Eu gostaria de..."
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: Problema que Resolve
      description: Explique qual problema esta feature resolveria
      placeholder: "Esta feature resolveria o problema de..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Solução Proposta
      description: Descreva como você imagina que esta feature deveria funcionar
      placeholder: "Eu imagino que..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Descreva outras soluções ou features que você considerou
      placeholder: "Eu também considerei..."

  - type: textarea
    id: additional-context
    attributes:
      label: Contexto Adicional
      description: Adicione qualquer contexto adicional, screenshots ou exemplos
      placeholder: "Qualquer informação adicional..."